const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('electronAPI', {
  openFloatWindow: () => ipcRenderer.send('open-float-window'),
  closeFloatWindow: () => ipcRenderer.send('close-float-window'),
  minimizeFloatWindow: () => ipcRenderer.send('minimize-float-window'),
  hideFloatWindow: () => ipcRenderer.send('hide-float-window'),
  dragFloatWindow: (dx, dy) => ipcRenderer.send('float-window-drag', { dx, dy }),
  setFloatOpacity: (opacity) => ipcRenderer.send('float-set-opacity', { opacity }),
  setFloatAlwaysOnTop: (onTop) => ipcRenderer.send('float-set-always-on-top', { onTop }),
  setFloatClickThrough: (enabled) => ipcRenderer.send('float-set-click-through', { enabled }),
  resizeFloatWindow: (w, h) => ipcRenderer.send('float-resize', { w, h }),
  onFloatClickThroughChanged: (cb) => ipcRenderer.on('float-click-through-changed', cb),
  getGoogleOAuthStatus: () => ipcRenderer.invoke('google-oauth-status'),
  saveGoogleOAuthConfig: (params) => ipcRenderer.invoke('google-oauth-save-config', params),
  clearGoogleOAuthConfig: () => ipcRenderer.invoke('google-oauth-clear-config'),
  startGoogleOAuth: (params) => ipcRenderer.invoke('google-oauth-start', params),
  refreshGoogleOAuth: (params) => ipcRenderer.invoke('google-oauth-refresh', params),
  setReminder: (time, todosJson) => ipcRenderer.invoke('reminder-set', { time, todosJson }),
  clearReminder: () => ipcRenderer.send('reminder-clear'),
  updateReminderTodos: (todosJson) => ipcRenderer.send('reminder-update-todos', { todosJson }),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  getUpdateStatus: () => ipcRenderer.invoke('get-update-status'),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  downloadUpdate: () => ipcRenderer.send('download-update'),
  installUpdate: () => ipcRenderer.send('install-update'),
  onUpdateAvailable: (cb) => ipcRenderer.on('update-available', cb),
  onUpdateNotAvailable: (cb) => ipcRenderer.on('update-not-available', cb),
  onUpdateDownloading: (cb) => ipcRenderer.on('update-downloading', cb),
  onUpdateProgress: (cb) => ipcRenderer.on('update-progress', cb),
  onUpdateDownloaded: (cb) => ipcRenderer.on('update-downloaded', cb),
  onUpdateError: (cb) => ipcRenderer.on('update-error', cb),
  icloudSave: (data) => ipcRenderer.invoke('icloud-save', data),
  icloudLoad: () => ipcRenderer.invoke('icloud-load'),
})
